export { default as VehiclesSchema } from './vehicles'
export { default as BrandsSchema } from './brands'
export { default as ModesSchema } from './modes'
export { default as VersionsSchema } from './versions'
export { default as CategoriesSchema } from './categories'
export { default as OptionalsSchema } from './optionals'
export { default as FuelsSchema } from './fuels'
export { default as ColorsSchema } from './colors'
