export { default as autoInject } from './autoInject'
export { default as plain } from './plain'
export { default as post } from './post'
export { default as forgotPasswordSendPin } from './forgotPasswordSendPin'
export { default as forgotPassword } from './forgotPassword'
export { default as updatePassword } from './updatePassword'
